version: '3'

services:
  app:
    image: ruby
    command: bash
    working_dir: /app
    depends_on:
      - redis
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    #network_mode: host

  redis:
    image: redis

volumes:
  bundle:
    external: true
